query Categories {
  categories (pagination: { page: 1, pageSize: 10 }) {
    data {
        id
        attributes {
        name
        products (pagination: { page: 1, pageSize: 100 }) {
          data {
            id
        		attributes {
              title
              image {
          			data {
            			attributes {
                    url
                  }
                }
              }
              description
        			price
        			custom_field {
            		title
            		required
            		options
        			}
            }
          }
        }
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}