query Slideshows {
  slideshows {
    data{
      id
      attributes{
        name
        img {
          data {
            attributes {
              url
            }
          }
        }
      }
    }    
  }
}