query Products ($key: String!, $pagesize: Int!, $page: Int!) {
  products (filters: { categories: { name: { eq: $key } } },pagination: { page: $page, pageSize: $pagesize } ) {
    data{
      id
      attributes{
        title
        price
        image {
          data {
            attributes {
              url
            }
          }
        }
        description
        categories {
          data {
            attributes {
                name
            }
          }
     	 	}
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}